server:
    port: 8081

spring:
    application:
        name: SolTracker

    datasource:
        url: jdbc:postgresql://localhost:5432/sol
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        open-in-view: false
        properties:
            hibernate:
                default_schema: sol
        hibernate:
            ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        schemas: sol
        enabled: true
        locations: classpath:db/postgres/migration


    cache:
        type: caffeine
        caffeine:
            spec: maximumSize=500,expireAfterWrite=10m

app:
    datasource:
        clickhouse:
            url: jdbc:clickhouse://localhost:8123/default?compress=0
            username: default
            password: 123456
            driver-class-name: com.clickhouse.jdbc.ClickHouseDriver