### get last Solana slot
GET http://localhost:8081/api/slots/last

### get transactios by last Solana slot
GET http://localhost:8081/api/slots/414104421/transactions

### get transactios by last Solana slot
POST https://api.mainnet-beta.solana.com
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "getBlock",
  "params": [
    232820360,
    {
      "encoding": "json",
      "transactionDetails": "full",
      "rewards": false,
      "maxSupportedTransactionVersion": 0
    }
  ]
}

### create Solana wallet
POST http://localhost:8081/api/solana/wallets

### create Solana wallet by address
POST http://localhost:8081/api/solana/wallets/by-address
Content-Type: application/json

{
  "address": "3rt9NicPSxztngD5brK8nVZ6GqR5WiCtp3HPyJjgmi1p"
}

### get transactios history by Solana address
GET http://localhost:8081/api/solana/wallets/3rt9NicPSxztngD5brK8nVZ6GqR5WiCtp3HPyJjgmi1p/history